#!/bin/bash
#PBS -N diag_hpx_batch
#PBS -A UCSD0085
#PBS -q casper
#PBS -l select=1:ncpus=8:ngpus=1:mem=40GB:gpu_type=a100
#PBS -l walltime=00:20:00
#PBS -o /glade/u/home/praggarwal/couple/output/logs/diag_hpx_batch.log
#PBS -j oe
set -euo pipefail
module load conda
conda activate /glade/work/praggarwal/conda-envs/atm
cd /glade/u/home/praggarwal/couple
export PYTHONWARNINGS=ignore
python -u scripts/diag_hpx_batch.py
